---
server:
  port: 8080
  contextPath: /SpringBootDemo
---
datasource:
  app:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: haaujdk
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

